name: awesome-kuberenetes-workflows
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: trigger remote sync to yks0000/yogeshsharma.me
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: yks0000
          repo: yogeshsharma.me
          ref: master
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: master.yml
